CREATE TABLE
    LITERALS
    (
        ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
        I1 INTEGER NOT NULL,
        I2 INTEGER NOT NULL,
        I3 INTEGER NOT NULL,
        C CHAR(1) NOT NULL,
        B SMALLINT NOT NULL,
        S SMALLINT NOT NULL,
        N1 BIGINT NOT NULL,
        N2 BIGINT NOT NULL,
        N3 BIGINT NOT NULL,
        F1 DOUBLE NOT NULL,
        F2 DOUBLE NOT NULL,
        F3 DOUBLE NOT NULL,
        D1 DOUBLE NOT NULL,
        D2 DOUBLE NOT NULL,
        PRIMARY KEY (ID)
    );